<a href="https://colab.research.google.com/github/gmrdns03/DataSciencePython_Minkyo/blob/main/03_%ED%85%8C%EC%9D%B4%EB%B8%94%ED%98%95_%EC%88%98%EC%B9%98_%EB%8D%B0%EC%9D%B4%ED%84%B0_%EB%8B%A4%EB%A3%A8%EA%B8%B0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

10개의 양수로 된 간단한 numpy배열 만들기

In [ ]:
# 넘파이에서는 리스트 내포를 안해도 알아서 넣어준다.
import numpy as np

# 배열 만들기 array()
numbers = np.array(range(1, 11), copy=True)
numbers





array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

ones() -> 1, zeros() -> 0, empty() -> 아직 생성되지 않은 엔트리로 구성(빈 방) <br>
일단 그릇을 만드는 설정만 하고 싶을 경우(초기 데이터)<br>
https://numpy.org/doc/stable/reference/generated/numpy.array.html


In [ ]:
# 아직 생성되지 않은 엔트리로 구성된 배열을 1로 채움
ones = np.ones([2,4], dtype=np.float64)  # shape자리에는 무조건 자리를 만들어줘야 한다. defqult값은 float
ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
# 아직 생성되지 않은 엔트리로 구성된 배열을 0로 채움
zeros = np.zeros([2,4], dtype=np.float64)
zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
# 아직 생성되지 않은 엔트리로 구성된 배열
empty = np.empty([2,4], dtype=np.float64)
empty

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

### 데이터 확인하기

In [ ]:
# 텍스트로 봤을 때 형태와 코드로 가져왔을 때 형태가 어떻게 다른지 확인해봐야함
# 데이터를 가져왔을 때 형태를 보는 shape을 반드시 본다.
ones.shape

(2, 4)

In [ ]:
# dimentio차원 보기
ones.ndim

2

In [ ]:
ones.dtype

dtype('float64')

In [ ]:
numbers.dtype

dtype('int64')

### arange(start, stop, step, dtype=None) 일정 간격으로 배열 생성하는 함수


In [ ]:
# arange(start, stop, step, dtype=None) 일정 간격으로 배열 생성하는 함수
np_numbers = np.arange(2, 5, 0.25)  # stop자리의 수는 포함이 되지 않는다.
np_numbers

array([2.  , 2.25, 2.5 , 2.75, 3.  , 3.25, 3.5 , 3.75, 4.  , 4.25, 4.5 ,
       4.75])

### astype(dtype, casting="unsafe", copy=True) 아이템의 타입 변경해 주는 함수


In [ ]:
np_numbers.dtype

dtype('float64')

In [ ]:
# 데이터 타입을 변경 시켜주는 함수
# astype에 한번 넣어주면 안에 있는 요솟값들을 전부 한번에 변경해준다.
np_numbers = np_numbers.astype(np.int)
np_numbers.dtype

dtype('int64')

### reshape(d0, d1, ...) 대상 배열의 모양을 바꿔주는 함수


In [ ]:
# 몇 가지 S&P 주식 기호들
sap = np.array(["MMM", "ABT", "ABBV", "ACN", "ACE", "ATVI", "ADBE", "ADT"])
sap #U4 는 4글자 유니코드


array(['MMM', 'ABT', 'ABBV', 'ACN', 'ACE', 'ATVI', 'ADBE', 'ADT'],
      dtype='<U4')

In [ ]:
sap.shape

(8,)

In [ ]:
# 말도 안되는 쉐입을 만들면 오류가 난다.
# 데이터 보존의 법칙, 데이터가 삭제되면 안된다.
sap2d = sap.reshape(2,4)

sap2d

array([['MMM', 'ABT', 'ABBV', 'ACN'],
       ['ACE', 'ATVI', 'ADBE', 'ADT']], dtype='<U4')

In [ ]:
# 기존 배열과 새로운 배열의 아이템의 개수는 항상 동일 해야 함
# numpy 보존의 법칙 성립

sap3d = sap.reshape(2,2,2) # 3차원으로 변경
sap3d

array([[['MMM', 'ABT'],
        ['ABBV', 'ACN']],

       [['ACE', 'ATVI'],
        ['ADBE', 'ADT']]], dtype='<U4')

In [ ]:
sap3d[0] # 1차원

array([['MMM', 'ABT'],
       ['ABBV', 'ACN']], dtype='<U4')

In [ ]:
sap3d[1] # 2차원

array([['ACE', 'ATVI'],
       ['ADBE', 'ADT']], dtype='<U4')

In [ ]:
sap3d[2] # 3차원
# 해당하는 데이터가 없어서 오류가 난다.
# 실무에서는 잘 쓰지 않는다.

IndexError: ignored

### 데이터 클리닝(data cleaning)을 위해 사용 되는 boolean indexing


In [ ]:
# 절대 음수 값이 와서는 안되는 데이터셋

dirty = np.array([9,4,1,-0.01,-0.002,-0.01])
whos_dirty = dirty < 0  # boolean indexing
whos_dirty

# array([False, False, False,  True,  True,  True])
# 항상 True일 때 무언가를 적용하기 쉽기 때문에 지우고 싶은 것들을 True로 만든 것

array([False, False, False,  True,  True,  True])

In [ ]:
dirty[whos_dirty] = 0 
# 모든 음수를 0으로 바꿔줌, True값들을 해당 요솟값으로 바꾸는 것
dirty

array([9., 4., 1., 0., 0., 0.])

### 논리 연산자 | or, & and, - not 결합하여 boolean indexing 사용


In [ ]:
linear = np.arange(-1, 1.1, 0.2)
linear

array([-1.00000000e+00, -8.00000000e-01, -6.00000000e-01, -4.00000000e-01,
       -2.00000000e-01, -2.22044605e-16,  2.00000000e-01,  4.00000000e-01,
        6.00000000e-01,  8.00000000e-01,  1.00000000e+00])

In [ ]:
# -0.5 ~ 0.5 사이의 값만 -> 0으로 변경하고 싶음
whos_linear = (linear <= 0.5) & (linear >= -0.5)  # 괄호를 씌워주는 버릇을 들여야 여러개의 조건을 걸 때 헷갈리지 않는다.
whos_linear


array([False, False, False,  True,  True,  True,  True,  True, False,
       False, False])

In [ ]:
linear[whos_linear] = 0
linear

array([-1. , -0.8, -0.6,  0. ,  0. ,  0. ,  0. ,  0. ,  0.6,  0.8,  1. ])

### 스마트 인덱싱

In [ ]:
sap

array(['MMM', 'ABT', 'ABBV', 'ACN', 'ACE', 'ATVI', 'ADBE', 'ADT'],
      dtype='<U4')

In [ ]:
# S&P 리스트에서 두번째, 세번째, 마지막 주식 기호를 추출
sap[[1,2,-1]]


array(['ABT', 'ABBV', 'ADT'], dtype='<U4')

In [ ]:
sap2d

array([['MMM', 'ABT', 'ABBV', 'ACN'],
       ['ACE', 'ATVI', 'ADBE', 'ADT']], dtype='<U4')

In [ ]:
sap2d[: , [1]]  # 대괄호로 감싸면 하나의 요소가 하나의 차원이 된다.
# : 을 붙이면 전체에서 슬라이싱 할 건데, 뒤에 있는 인덱싱에 있는 방법을 가져와라

array([['ABT'],
       ['ATVI']], dtype='<U4')

In [ ]:
sap2d[:, 1]

array(['ABT', 'ATVI'], dtype='<U4')

### 차원만 같다면 numpy에서는 사칙연산 가능 (그낭 더하기) -> 브로드캐스팅


In [ ]:
a = np.arange(4)
b = np.arange(1, 5)

print(a)
print(b)

[0 1 2 3]
[1 2 3 4]


In [ ]:
# 데이터를 numpy 배열에만 넣을 수 있다면 편리한 계산이 가능하다.
a+b

array([1, 3, 5, 7])

In [ ]:
a * 5

array([ 0,  5, 10, 15])

In [ ]:
np.random.random([4, 4])

array([[0.13773616, 0.02422886, 0.11123668, 0.55427959],
       [0.77227791, 0.89466114, 0.81921547, 0.72896944],
       [0.44619527, 0.08782578, 0.76856718, 0.48592457],
       [0.26155894, 0.78267376, 0.62300394, 0.42386271]])

In [ ]:
noise = np.eye(4) + 0.01 * np.random.random([4, 4])
noise

array([[1.0057593 , 0.00332819, 0.0077765 , 0.00806917],
       [0.00410368, 1.00438182, 0.00340789, 0.00373321],
       [0.00835538, 0.00687734, 1.00551018, 0.00297917],
       [0.00775943, 0.00109953, 0.00176918, 1.00935239]])